services:

  reverse-proxy:
    image: caddy:latest
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/pages:/srv
      - ./caddy/certs:/certs
    ports:
      - 80:80
      - 443:443

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    volumes:
      - ./app:/app/
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

volumes:
  postgres_data:
