services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./.env.app.dev
    ports:
      - "8080:80"
    volumes:
      - ./app:/app/
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
volumes:
  postgres_data:
