services:

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    volumes:
      - ./app:/app/
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

volumes:
  postgres_data:

networks:
  default:
    name: server
    external: true
