[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:{{ env "TRAEFIK_PASSWORD" }}"
  ]

[http.routers.api]
  rule = "Host(`monitor.hadam.us`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"